version: '3'
services:
  node:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"
    volumes:
      - ./.ethereum_data:/ethereum_data
    entrypoint:
      - node
      - ./build/cli.node.js
      - -n
      - -a
      - '10'
      - --db=/ethereum_data

networks:
  default:
  #   external:
  #     name: ${NETWORK:-webproxy}
  # outside:
    external:
      name: ${SERVICE_NETWORK:-webservices}
